### ISSUE TITLE
There is a minor typo in the bash script

### ISSUE THREAD

**Issue by noob-ja** [vlomonaco/core50#2]
Instead of
unzip $DIR/../../data/core50_128x128.zipfile.zip -d $DIR/../../data/

It should be
unzip $DIR/../../data/core50_128x128.zip -d $DIR/../../data/

**Comment by vlomonaco** [comment]
Hi @noob-ja! Thanks for the heads up :100: :smile: 
Fixed in the last commit: d36a97fa63b057f083b3cd83438b7b2b3f35d3fc
