### ISSUE TITLE
pytorch support

### ISSUE THREAD

**Issue by arccoxx** [vlomonaco/core50#3]
Hello, 

I am working with models in pytorch. This is an awesome benchmark. Can you help me benchmark my pytorch model? Can you help me set up this environment? Awesome work I'm kinda surprised no ones tried to get a good score on this.

Let's get a high score!

Best,

Aidan

**Comment by vlomonaco** [comment]
Hi @arccoxx thanks for your kind feedback! 

> I'm kinda surprised no ones tried to get a good score on this

For many CL algorithms CORe50 is still too complex I believe!

> Can you help me benchmark my pytorch model? Can you help me set up this environment?

Sure, have you looked in this repo? https://github.com/vlomonaco/ar1-pytorch It's the AR1 algorithm implemented in Pytorch and tested on CORe50!
