### ISSUE TITLE
Result on the paper

### ISSUE THREAD

**Issue by sunilhoho** [vlomonaco/core50#5]
Hello,

![캡처](https://user-images.githubusercontent.com/83444951/158001699-6b08be0c-abf4-4897-ae3c-c88976887ecc.PNG)

In my understanding Table 2 in your paper, CORe50: a New Dataset and Benchmark for Continuous Object Recognition, is the result after only 1epoch training(Online Learning setting) on CORe50. Am I right? Or is it the result after multi-epoch training? If it is, how many epochs did you train?

Best,

Sunil

**Comment by vlomonaco** [comment]
Hi @sunilhoho! thanks for reaching out. These results were obtained with multiple epochs till convergence. I cannot recall the specific number of epochs for each method, sorry.

**Comment by sunilhoho** [comment]
Thanks. Your comment really helps me.
